[package]
name = "hulc2envolventecte"
version = "0.1.0"
authors = ["Rafael Villar Burke <pachi@ietcc.csic.es>"]
edition = "2018"

[dependencies]
encoding = "0.2"
exitfailure = "0.5.1"
failure = "0.1.5"
glob = "0.2"
serde = "1.0.88"
serde_json = "1.0.38"
serde_derive = "1.0.88"
uuid = { version = "0.7.2", features = ["v4"] }
winapi = { version = "0.3.6", features = ["wingdi", "winuser", "libloaderapi", "combaseapi", "objbase", "shobjidl", "shlobj", "winerror"] }

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
incremental = false
opt-level = "z"