[workspace]

repository = "https://github.com/pachi/cteenergymodel"
members = [
    "bemodel", "climate", "hulc", "hulc2model", "hulc_tests"
]

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
incremental = false
opt-level = "z"
