[workspace]

members = [
    "bemodel", "climate", "hulc", "hulc2model", "hulc_tests", "convertdb"
]

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
incremental = false
opt-level = "z"
# Modificación para mejorar info de flamegraph
debug = true


[profile.bench]
debug = true
